/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArchiveVisits: typeof import('./src/components/ArchiveVisits.vue')['default']
    AssetCarSection: typeof import('./src/components/forms/AssetCarSection.vue')['default']
    AuditorInformation: typeof import('./src/components/AuditorInformation.vue')['default']
    BesogsbrevButton: typeof import('./src/components/forms/BesogsbrevButton.vue')['default']
    BFormRadioGroup: typeof import('bootstrap-vue-next/components/BFormRadio')['BFormRadioGroup']
    BlancoForm: typeof import('./src/components/forms/BlancoForm.vue')['default']
    CardStatusField: typeof import('./src/components/CardStatusField.vue')['default']
    ContactSection: typeof import('./src/components/forms/ContactSection.vue')['default']
    CreateUser: typeof import('./src/components/CreateUser.vue')['default']
    CreateVisits: typeof import('./src/components/CreateVisits.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DebitorPanel: typeof import('./src/components/forms/DebitorPanel.vue')['default']
    DocxPdfViewer: typeof import('./src/components/DocxPdfViewer.vue')['default']
    FileUpload: typeof import('./src/components/forms/FileUpload.vue')['default']
    FormActions: typeof import('./src/components/forms/FormActions.vue')['default']
    FormHeader: typeof import('./src/components/forms/FormHeader.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    KonsulentCard: typeof import('./src/components/KonsulentCard.vue')['default']
    LeasingForm: typeof import('./src/components/forms/LeasingForm.vue')['default']
    LetterForm: typeof import('./src/components/forms/LetterForm.vue')['default']
    MoneyRangeSelector: typeof import('./src/components/forms/MoneyRangeSelector.vue')['default']
    NonPlannedVisits: typeof import('./src/components/NonPlannedVisits.vue')['default']
    NotVisitedVisits: typeof import('./src/components/NotVisitedVisits.vue')['default']
    OtherAssetsSection: typeof import('./src/components/forms/OtherAssetsSection.vue')['default']
    PaymentSection: typeof import('./src/components/forms/PaymentSection.vue')['default']
    PlannedVisits: typeof import('./src/components/PlannedVisits.vue')['default']
    PlanVisits: typeof import('./src/components/PlanVisits.vue')['default']
    PrintDayButton: typeof import('./src/components/PrintDayButton.vue')['default']
    PropertySection: typeof import('./src/components/forms/PropertySection.vue')['default']
    PurchaseForm: typeof import('./src/components/forms/PurchaseForm.vue')['default']
    ReviewVisits: typeof import('./src/components/ReviewVisits.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('./src/components/forms/SelectField.vue')['default']
    SendVisitLetter: typeof import('./src/components/SendVisitLetter.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UpdateUser: typeof import('./src/components/UpdateUser.vue')['default']
    VisitCard: typeof import('./src/components/VisitCard.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    YesNo: typeof import('./src/components/forms/YesNo.vue')['default']
  }
}
